spring.application.name=ms-hotel-rooms

server.port=${PORT: 8080}

app.public-host=${PUBLIC_HOST_URL:http://localhost:8080}



logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_RGh4stkX2
app.gateway.secret=${API_GATEWAY_SECRET:secreto_local}

# --- SUPABASE (POSTGRESQL) ---
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Dialecto para H2

spring.datasource.url=jdbc:h2:mem:hoteldb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Habilitar consola web de H2 (para ver la base de datos visualmente)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console