spring.application.name=ms-hotel-rooms

server.port=${PORT: 8080}

app.public-host=${PUBLIC_HOST_URL:http://localhost:8080}



logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_RGh4stkX2
app.gateway.secret=${API_GATEWAY_SECRET:secreto_local}